export const styles = {
  parentContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#f0f0f0', 
  },
  container: {
    position: 'relative',
    padding: '20px',
    background: '#fff',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    maxWidth: '100%',
    width: '100%',
    fontFamily: 'Marck Script',
    boxSizing: 'border-box',
  },
  closeButton: {
    position: 'absolute',
    top: '-15px',
    right: '-15px',
    width: '35px',
    height: '35px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: '50%',
    border: '2px groove #fff',
    cursor: 'pointer',
  },
  closeIcon: {
    fontSize: '20px',
    color: '#888',
  },
  inputGroup: {
    marginBottom: '16px',
  },
  label: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '6px',
    display: 'block',
  },
  titleInput: {
    width: '100%',
    padding: '8px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    boxSizing: 'border-box',
  },
  contentTextarea: {
    width: '100%',
    padding: '8px',
    fontSize: '16px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  tagsContainer: {
    marginBottom: '16px',
  },
  radioGroup: {
    display: 'flex',
    justifyContent: 'space-around',
    marginBottom: '16px',
  },
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#333',
  },
  errorText: {
    color: '#f00',
    fontSize: '14px',
    marginBottom: '16px',
  },
  submitButton: {
    width: '100%',
    padding: '12px',
    fontSize: '18px',
    background: 'linear-gradient(to right, #015f5f, #028090, #00a896)',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
};