export const styles = {
    container: {
      margin: "0 auto",
      padding: "0 16px",
      maxWidth: "1200px",
      height: '75vh',

    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
      gap: "20px",
      marginTop: "32px",
    },
    button: {
      width: "64px",
      height: "64px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "50%",
      background: "linear-gradient(to right, #015f5f, #028090, #00a896)",
      fontFamily: "Marck Script",
      color: "#fff",
      fontSize: "32px",
      cursor: "pointer",
      position: "fixed",
      right: "40px",
      bottom: "40px",
      border: "3px groove #fff",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
    modalOverlay: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(0,0,0,0.6)",
      padding: "0",
    },
    modalContent: {
      width: "40%",
      maxHeight: "75%",
      backgroundColor: "white",
      borderRadius: "8px",
      padding: "20px",
      margin: "0",
      overflowY: "auto",
      position: "relative",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
    heading: {
      fontSize: "1.5rem",
      fontWeight: "600",
      marginTop: "20px",
      color: "#333",
      textAlign: "center",
    },
  };
  