export const styles = {
  profileInfo: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "16px",
    borderRadius: "16px",
    background: "#f9f9f9",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    transition: "background-color 0.3s ease, box-shadow 0.3s ease, transform 0.3s ease",
  },
  profileInfoHover: {
    background: "#e0f7fa",
    boxShadow: "0 6px 12px rgba(0, 0, 0, 0.15)",
    transform: "scale(1.02)",
  },
  avatar: {
    width: "56px",
    height: "56px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "#028090",
    color: "#fff",
    fontSize: "24px",
    fontWeight: 600,
    border: "3px groove #fff",
    transition: "background-color 0.3s ease, transform 0.3s ease",
  },
  avatarHover: {
    backgroundColor: "#015f5f",
    transform: "scale(1.05)",
  },
  userDetails: {
    display: "flex",
    flexDirection: "column",
  },
  userName: {
    fontSize: "18px",
    fontWeight: 600,
    color: "#333",
    margin: 0,
    fontFamily: "Marck Script",
    transition: "color 0.3s ease",
  },
  userNameHover: {
    color: "#028090",
  },
  logoutLink: {
    fontSize: "16px",
    color: "#fff",
    textDecoration: "none",
    cursor: "pointer",
    padding: "10px 20px",
    borderRadius: "5px",
    border: "none",
    backgroundColor: "#028090",
    fontWeight: "bold",
    outline: "none",
    transition: "background-color 0.3s ease, transform 0.3s ease, color 0.3s ease",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  logoutLinkHover: {
    backgroundColor: "#015f5f",
    transform: "scale(1.05)",
    color: "#e0f7fa",
  },
};
