export const styles = {
    container: {
      marginTop: '0.5rem',
    },
    tagsContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      flexWrap: 'wrap',
      marginTop: '0.5rem',
    },
    tag: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      fontSize: '0.875rem',
      color: '#1a202c',
      backgroundColor: '#f7fafc',
      padding: '0.25rem 0.75rem',
      borderRadius: '0.375rem',
    },
    removeButton: {
      border: 'none',
      background: 'none',
      cursor: 'pointer',
      color: '#4a5568',
    },
    inputContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '1rem',
      marginTop: '0.75rem',
    },
    input: {
      fontSize: '0.875rem',
      backgroundColor: 'transparent',
      border: '1px solid #e2e8f0',
      padding: '0.5rem 0.75rem',
      borderRadius: '0.375rem',
      outline: 'none',
      width: '100%',
    },
    addButton: {
      width: '2rem',
      height: '2rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '0.375rem',
      border: '1px solid #2b6cb0',
      backgroundColor: '#e2e8f0',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease',
    },
    addButtonIcon: {
      fontSize: '1.5rem',
      color: '#2b6cb0',
    },
    addButtonHover: {
      backgroundColor: '#2b6cb0',
      color: '#ffffff',
    },
  };